name = "simplemergepdf"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[r2_buckets]]
binding = "MERGED_PDFS"
bucket_name = "simplemergepdf-merged"

[observability]
enabled = true